apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  creationTimestamp: null
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      nodeSelector:
        worker_2: "true" 
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: DN_NAME
        volumeMounts:
        - name: myvol
          mountPath: /var/lib/mysql
      volumes:
      - name: myvol
        persistentVolumeClaim:
          claimName: mysql-pvc
